services:
  server:
    image: ijproblems
    build:
      dockerfile: ./Dockerfile
    container_name: ijproblems-server
    environment:
      FASTAPI_PORT: 8000
      FASTAPI_HOST: 0.0.0.0
      FASTAPI_RELOAD: 1
      GITHUB_APP_CLIENT_ID:
      GITHUB_APP_CLIENT_SECRET:
      SESSION_SECRET:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
      USE_MOCK:
      DUMMY_LOGIN:
    ports:
      - "8000:8000"
    volumes:
      - ./:/app/.
    restart: "no"
    networks:
      - backend_network

  postgres:
    image: postgres:16.1
    container_name: ijproblems-postgres
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
    hostname: postgres
    ports:
      - "5432:5432"
    volumes:
      - .postgres-data:/var/lib/postgresql/data
      - ./sql:/sql
    restart: "no"
    networks:
      - backend_network

  admin:
    image: ijproblems-admin
    build:
      dockerfile: ./admin/Dockerfile
    container_name: ijproblems-admin
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
      ADMIN_SHEET_ID:
    volumes:
      - ./admin:/admin
    stdin_open: true
    tty: true
    restart: "no"
    networks:
      - backend_network

  nginx:
    image: nginx:1.25.4
    container_name: ijproblems-nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/static
    depends_on:
      - server
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
